### ISSUE TITLE
Localization mode creates new map cloud

### ISSUE THREAD

**Issue by martinlucan** [introlab/rtabmap_ros#997] opened 2023-07-12 20:05 UTC
Hi there,

I try to run RTAB-Map in localization mode in the previously generated map. When I launch the localization approx. at the position where the mapping started, the result is correct and localization runs smoothly. Although, when the localization is launched in a different part of the map, RTAB-MAP does not find a global position in the map and starts to create a new map cloud. Please, is there any setting that helps to avoid this? Is RTAB-Map supposed to find a position when launched anywhere in the map? Thanks.

**Comment by matlabbe** [comment] 2023-07-14 16:10
Duplicate of http://official-rtab-map-forum.206.s1.nabble.com/Localization-creates-new-map-cloud-td9552.html#a9564

**Closed by matlabbe** 2023-07-14 16:10 UTC
