### ISSUE TITLE
run RTAB-MAP but without image open

### ISSUE THREAD

**Issue by JingqiuZuo** [introlab/rtabmap_ros#285] opened 2018-11-11 06:18 UTC
Hello all!

Please help me with my problems.

After download and install rtabmap_ros, I run `roslaunch rtabmap_ros rtabmap.launch rtabmap_args:="--delete_db_on_start" depth_topic:=/camera/aligned_depth_to_color/image_raw rgb_topic:=/camera/color/image_raw camera_info_topic:=/camera/color/camera_info` in the terminal.

Then the RTAB-MAP run, but like this picture:
![screenshot from 2018-11-11 15-04-35](https://user-images.githubusercontent.com/36063847/48309800-73907d80-e5c4-11e8-9b05-a227179a7b0a.png)
It didn't have any image output.

And the terminal also have warning:

[ WARN] [1541916269.544172735]: /rtabmap/rgbd_odometry: Did not receive data since 5 seconds! Make sure the input topics are published ("$ rostopic hz my_topic") and the timestamps in their header are set. 
/rtabmap/rgbd_odometry subscribed to (approx sync):
   /camera/color/image_raw,
   /camera/aligned_depth_to_color/image_raw,
   /camera/color/camera_info
[ WARN] [1541916270.303259059]: /rtabmap/rtabmap: Did not receive data since 5 seconds! Make sure the input topics are published ("$ rostopic hz my_topic") and the timestamps in their header are set. If topics are coming from different computers, make sure the clocks of the computers are synchronized ("ntpdate"). If topics are not published at the same rate, you could increase "queue_size" parameter (current=10).
/rtabmap/rtabmap subscribed to (approx sync):
   /rtabmap/odom,
   /camera/color/image_raw,
   /camera/aligned_depth_to_color/image_raw,
   /camera/color/camera_info,
   /rtabmap/odom_info
[ WARN] [1541916270.530203041]: /rtabmap/rtabmapviz: Did not receive data since 5 seconds! Make sure the input topics are published ("$ rostopic hz my_topic") and the timestamps in their header are set. If topics are coming from different computers, make sure the clocks of the computers are synchronized ("ntpdate"). If topics are not published at the same rate, you could increase "queue_size" parameter (current=10).
/rtabmap/rtabmapviz subscribed to (approx sync):
   /rtabmap/odom,
   /camera/color/image_raw,
   /camera/aligned_depth_to_color/image_raw,
   /camera/color/camera_info,
   /rtabmap/odom_info

**Comment by matlabbe** [comment] 2018-11-11 16:33
Duplicate of https://answers.ros.org/question/308137/run-rtab-map-but-without-image-open/

**Closed by matlabbe** 2018-11-11 16:33 UTC
