### ISSUE TITLE
Reconstruction not showing in RVIZ  

### ISSUE THREAD

**Issue by yohannes-taye** [introlab/rtabmap_ros#486] opened 2020-10-25 09:45 UTC
Here is my issue

I have just setup rtabmap and the visualization in rtabmapviz is working just as intended but while trying to use RViz its not showing the reconstruction at all. I looked at the demo on the website and the reconstruction is rendered by subscribing to a /assembled_cloud topic which is not showing up in the topics list while I run rostopic list. Am I missing something here?
![image](https://user-images.githubusercontent.com/32170806/97103800-d0ba6680-16e9-11eb-8fa9-d6dd8aaf7205.png)

**Comment by matlabbe** [comment] 2020-11-06 20:49
Duplicate of https://github.com/introlab/rtabmap/issues/619

**Closed by matlabbe** 2020-11-06 20:49 UTC
