### ISSUE TITLE
Loop closure hypothesis rejected

### ISSUE THREAD

**Issue by ammar-n-abbas** [introlab/rtabmap_ros#540] opened 2021-02-15 11:04 UTC
Loop closure hypothesis rejected during mapping while driving forward and reverse to capture similar point of view, the points are mapped crossing each other, any idea?

![Screenshot from 2021-02-15 16-02-39](https://user-images.githubusercontent.com/28593585/107938498-4f902380-6fa7-11eb-8c27-8e10f45b92c7.png)
 
Thanks in advance

**Comment by matlabbe** [comment] 2021-02-21 18:57
duplicate of http://official-rtab-map-forum.67519.x6.nabble.com/RTAB-Map-loop-closure-issue-td7472.html

**Closed by matlabbe** 2021-02-21 18:57 UTC
