### ISSUE TITLE
error: (-215) trainDescCollection[iIdx].rows < IMGIDX_ONE

### ISSUE THREAD

**Issue by kevinlyu1** [introlab/rtabmap_ros#83] opened 2016-06-09 14:37 UTC
has anyone ever encountered a problem that is "OpenCV Error: Assertion failed (trainDescCollection[iIdx].rows < IMGIDX_ONE) in KnnMatchImpl, file ../matchers.cpp, line 365 terminate called after throwing an instance of 'cv::Exception'"? I am getting it when I do long mapping sessions. For some reason I also get it even if I save one session and start another one. If anyone can help that would be great. I think I've attached the .png below.

![rtab_error](https://cloud.githubusercontent.com/assets/17326255/15933426/bb4efabc-2e2d-11e6-9749-c865075180d5.png)

**Comment by matlabbe** [comment] 2016-06-09 20:27
Hi,

you may want to activate the debug log of rtabmap node to see from where the opencv function is called:
```bash
$ rosservice call /rtabmap/rtabmap/log_debug
```

The referring assert in OpenCV is [here](https://github.com/Itseez/opencv/blob/2.4.8/modules/features2d/src/matchers.cpp#L365):
```cpp
    for( iIdx = 0; iIdx < imgCount; iIdx++ )
    {
        CV_Assert( trainDescCollection[iIdx].rows < IMGIDX_ONE );
        batchDistance(queryDescriptors, trainDescCollection[iIdx], dist, dtype, nidx,
                      normType, knn, masks.empty() ? Mat() : masks[iIdx], update, crossCheck);
        update += IMGIDX_ONE;
    }
```

The `trainDescCollection[0]` would be the `newWords` matrix from [there](https://github.com/introlab/rtabmap/blob/7c8583f0253897a8a5acfb22e2c3fb23f66026b5/corelib/src/VWDictionary.cpp#L1086) in rtabmap code (the only place it is called if all NN related parameters are set to KdTree which is the default):
```cpp
std::vector<std::vector<cv::DMatch> > matchesNewWords;
cv::BFMatcher matcher(descriptors.type()==CV_8U?cv::NORM_HAMMING:useDistanceL1_?cv::NORM_L1:cv::NORM_L2SQR);
matcher.knnMatch(descriptors.row(i), newWords, matchesNewWords, newWords.rows>1?2:1);
```

Well, `newWords` would have a maximum of 400 words (by default). The OpenCV assert happens if there are `IMGIDS_ONE` words in that matrix. IMGIDS_ONE is defined [here](https://github.com/Itseez/opencv/blob/2.4.8/modules/features2d/src/matchers.cpp#L343-L344):
```cpp
const int IMGIDX_SHIFT = 18;
const int IMGIDX_ONE = (1 << IMGIDX_SHIFT);
```

If you can have a debug log, it would help to see if the `newWords` matrix is somewhat corrupted.

cheers

**Comment by kevinlyu1** [comment] 2016-06-13 13:58
Thanks for the help. For some reason the error hasn't come up in the past few days of testing. So I am not sure if it's fixed or not.

Due to that should I close this issue or leave it open?

**Comment by matlabbe** [comment] 2016-06-13 14:10
I will close it as "not reproducible". If it happens again, just re-comment on this thread. 

cheers

**Closed by matlabbe** 2016-06-13 14:10 UTC

**Comment by siddharth-gitrepo** [comment] 2024-03-08 05:17
Have been facing this issue.

**Comment by matlabbe** [comment] 2024-03-09 23:09
Which opencv version are you using? Your example is purely opencv, I guess the issue is coming from opencv.

**Comment by matlabbe** [comment] 2026-03-24 17:16
Got the same issue after trying the graph reduction tool: https://github.com/introlab/rtabmap/pull/1655

**EDIT**: Can be reproduced before reducing the graph. This is after a new map has been appended to an old map using `rtabmap-reprocess -a` tool. The log is similar with the not-reduced map.

The debug log, it is asserting right on the first image added (this is in localization mode):
```
[ INFO] (2026-03-24 10:18:16.997) RtabmapThread.cpp:595::getData() wake-up
[DEBUG] (2026-03-24 10:18:16.997) Rtabmap.cpp:1210::process() 
[ INFO] (2026-03-24 10:18:16.997) Rtabmap.cpp:1271::process() getting data...
[DEBUG] (2026-03-24 10:18:16.997) Rtabmap.cpp:1329::process() incremental=0 odomPose=xyz=27.368610,-30.237593,0.000000 rpy=0.000000,-0.000000,0.071879 optimizedPoses=9382 mapCorrection=xyz=0.000000,0.000000,0.000000 rpy=0.000000,-0.000000,0.000000 lastLocalizationPose=xyz=-23.876450,87.445610,0.000000 rpy=0.000000,-0.000000,1.608911 lastLocalizationNodeId=0
[DEBUG] (2026-03-24 10:18:16.999) DBDriverSqlite3.cpp:3219::loadSignaturesQuery() Loading local features.... done! (in 0.002082 s)
[DEBUG] (2026-03-24 10:18:16.999) DBDriverSqlite3.cpp:3222::loadSignaturesQuery() Time loading links=0.000062s
[DEBUG] (2026-03-24 10:18:16.999) DBDriverSqlite3.cpp:3413::loadSignaturesQuery() Time load 1 calibrations=0.000332s
[DEBUG] (2026-03-24 10:18:16.999) DBDriverSqlite3.cpp:3480::loadSignaturesQuery() Time load 1 global descriptors=0.000026s
[DEBUG] (2026-03-24 10:18:17.000) Graph.cpp:2338::findNearestNodes() found nodes=1
[ WARN] (2026-03-24 10:18:17.000) Rtabmap.cpp:1362::process() Update map correction based on last localization saved in database! correction = xyz=-55.020714,61.113358,0.000000 rpy=0.000000,-0.000000,1.537032, nearest id = 13462 of last pose = xyz=-23.876450,87.445610,0.000000 rpy=0.000000,-0.000000,1.608911, odom = xyz=27.368610,-30.237593,0.000000 rpy=0.000000,-0.000000,0.071879
[ WARN] (2026-03-24 10:18:17.000) DBReader.cpp:552::getNextData() The node loaded (2) doesn't have neighbor, re-using the covariance of the previous link for odometry.
[ INFO] (2026-03-24 10:18:17.000) Rtabmap.cpp:1460::process() Updating memory...
[DEBUG] (2026-03-24 10:18:17.000) Memory.cpp:1026::update() 
[DEBUG] (2026-03-24 10:18:17.000) Memory.cpp:1035::update() pre-updating...
[DEBUG] (2026-03-24 10:18:17.000) Memory.cpp:6684::cleanUnusedWords() Removing 0 words (dictionary size=3661282)...
[DEBUG] (2026-03-24 10:18:17.000) Memory.cpp:1039::update() time preUpdate=0.010967 ms
[DEBUG] (2026-03-24 10:18:17.000) Memory.cpp:4848::createSignature() 
[DEBUG] (2026-03-24 10:18:17.000) Memory.cpp:5087::createSignature() Start dictionary update thread
[DEBUG] (2026-03-24 10:18:17.000) VWDictionary.cpp:477::update() incremental=1
[DEBUG] (2026-03-24 10:18:17.000) VWDictionary.cpp:687::update() Dictionary has not changed, so no need to update it! (size=3661282)
[DEBUG] (2026-03-24 10:18:17.000) VWDictionary.cpp:691::update() 
[DEBUG] (2026-03-24 10:18:17.000) Memory.cpp:5106::createSignature() Rotating camera 0
[DEBUG] (2026-03-24 10:18:17.000) util2d.cpp:2376::rotateImagesUpsideUpIfNecessary() roll=-0.006831 pitch=0.957982 yaw=1.549228
[DEBUG] (2026-03-24 10:18:17.000) util2d.cpp:2380::rotateImagesUpsideUpIfNecessary() Ignoring image rotation as pitch(0.957982)>Pi/4
[DEBUG] (2026-03-24 10:18:17.001) Memory.cpp:5106::createSignature() Rotating camera 1
[DEBUG] (2026-03-24 10:18:17.001) util2d.cpp:2376::rotateImagesUpsideUpIfNecessary() roll=0.015786 pitch=0.875079 yaw=0.000000
[DEBUG] (2026-03-24 10:18:17.001) util2d.cpp:2380::rotateImagesUpsideUpIfNecessary() Ignoring image rotation as pitch(0.875079)>Pi/4
[DEBUG] (2026-03-24 10:18:17.001) Memory.cpp:5106::createSignature() Rotating camera 2
[DEBUG] (2026-03-24 10:18:17.001) util2d.cpp:2376::rotateImagesUpsideUpIfNecessary() roll=-0.001426 pitch=0.985048 yaw=-1.587992
[DEBUG] (2026-03-24 10:18:17.001) util2d.cpp:2380::rotateImagesUpsideUpIfNecessary() Ignoring image rotation as pitch(0.985048)>Pi/4
[DEBUG] (2026-03-24 10:18:17.001) Memory.cpp:5106::createSignature() Rotating camera 3
[DEBUG] (2026-03-24 10:18:17.001) util2d.cpp:2376::rotateImagesUpsideUpIfNecessary() roll=0.000274 pitch=0.873383 yaw=3.117618
[DEBUG] (2026-03-24 10:18:17.001) util2d.cpp:2380::rotateImagesUpsideUpIfNecessary() Ignoring image rotation as pitch(0.873383)>Pi/4
[DEBUG] (2026-03-24 10:18:17.001) Memory.cpp:5185::createSignature() Received kpts=0 kpts3D=0, descriptors=0 _useOdometryFeatures=true
[ INFO] (2026-03-24 10:18:17.001) Memory.cpp:5247::createSignature() Extract features
[DEBUG] (2026-03-24 10:18:17.001) Memory.cpp:5330::createSignature() rawDescriptorsKept=1, pose=1, maxFeatures=500, visMaxFeatures=1000
[DEBUG] (2026-03-24 10:18:17.001) Memory.cpp:5335::createSignature() Changing temporary max features from 500 to 1000
Device Number: 0
  Device name: NVIDIA GeForce RTX 3080
  Memory Clock Rate (MHz): 9501
  Memory Bus Width (bits): 320
  Peak Memory Bandwidth (GB/s): 760.1

[DEBUG] (2026-03-24 10:18:17.009) Features2d.cpp:1295::parseParameters() Init SiftData
[DEBUG] (2026-03-24 10:18:17.010) util2d.cpp:1162::computeRoi() roi ratios = 0.000000, 0.000000, 0.000000, 0.000000
[DEBUG] (2026-03-24 10:18:17.010) util2d.cpp:1163::computeRoi() roi = 0, 0, 1920, 300
[DEBUG] (2026-03-24 10:18:17.010) util2d.cpp:1190::computeRoi() roi = 0, 0, 1920, 300
[DEBUG] (2026-03-24 10:18:17.012) MainWindow.cpp:1052::processOdometry() 
[DEBUG] (2026-03-24 10:18:17.012) MainWindow.cpp:1096::processOdometry() odom ok
[DEBUG] (2026-03-24 10:18:17.013) util3d.cpp:1204::cloudsRGBFromSensorData() 
[DEBUG] (2026-03-24 10:18:17.013) util3d.cpp:495::cloudFromDepthRGB() 
[DEBUG] (2026-03-24 10:18:17.013) util3d.cpp:605::cloudFromDepthRGB() rgb=480x300 depth=480x300 fx=204.242129 fy=204.160302 cx=233.701832 cy=149.382122 (depth factors=1.000000 1.000000) has confidence=0 (thr=3) decimation=4
[DEBUG] (2026-03-24 10:18:17.013) util3d.cpp:666::cloudFromDepthRGB() 
[DEBUG] (2026-03-24 10:18:17.013) util3d.cpp:495::cloudFromDepthRGB() 
[DEBUG] (2026-03-24 10:18:17.013) util3d.cpp:605::cloudFromDepthRGB() rgb=480x300 depth=480x300 fx=204.250998 fy=204.250998 cx=233.896993 cy=150.200973 (depth factors=1.000000 1.000000) has confidence=0 (thr=3) decimation=4
[DEBUG] (2026-03-24 10:18:17.013) util3d.cpp:666::cloudFromDepthRGB() 
[DEBUG] (2026-03-24 10:18:17.013) util3d.cpp:495::cloudFromDepthRGB() 
[DEBUG] (2026-03-24 10:18:17.013) util3d.cpp:605::cloudFromDepthRGB() rgb=480x300 depth=480x300 fx=204.367556 fy=204.041090 cx=235.801392 cy=148.545920 (depth factors=1.000000 1.000000) has confidence=0 (thr=3) decimation=4
[DEBUG] (2026-03-24 10:18:17.013) util3d.cpp:666::cloudFromDepthRGB() 
[DEBUG] (2026-03-24 10:18:17.014) util3d.cpp:495::cloudFromDepthRGB() 
[DEBUG] (2026-03-24 10:18:17.014) util3d.cpp:605::cloudFromDepthRGB() rgb=480x300 depth=480x300 fx=204.192870 fy=203.950552 cx=236.651425 cy=150.813240 (depth factors=1.000000 1.000000) has confidence=0 (thr=3) decimation=4
[DEBUG] (2026-03-24 10:18:17.014) util3d.cpp:666::cloudFromDepthRGB() 
[DEBUG] (2026-03-24 10:18:17.016) MainWindow.cpp:1584::processOdometry() Time 3D Rendering: 0.003428s
[DEBUG] (2026-03-24 10:18:17.016) CloudViewer.cpp:1687::updateCoordinatePose() Updating pose reference to xyz=27.368610,-30.237593,0.000000 rpy=0.000000,-0.000000,0.071879
[DEBUG] (2026-03-24 10:18:17.017) MainWindow.cpp:1636::processOdometry() Time Update Pose: 0.001133s
[DEBUG] (2026-03-24 10:18:17.031) Features2d.cpp:1369::generateKeypointsImpl() numOctaves=6 initBlur=1.600000 thresh=2.000000 edgeLimit=10.000000 minScale=0.000000 upScale=false w=1920 h=300
[DEBUG] (2026-03-24 10:18:17.033) MainWindow.cpp:1643::processOdometry() Time Update graphview: 0.016272s
[DEBUG] (2026-03-24 10:18:17.034) Features2d.cpp:1385::generateKeypointsImpl() 1153 features extracted
[DEBUG] (2026-03-24 10:18:17.035) Features2d.cpp:858::generateKeypoints() Keypoints extraction time = 0.024168 s, keypoints extracted = 919 (grid=1x1, mask empty=0)
Device Number: 0
  Device name: NVIDIA GeForce RTX 3080
  Memory Clock Rate (MHz): 9501
  Memory Bus Width (bits): 320
  Peak Memory Bandwidth (GB/s): 760.1

[DEBUG] (2026-03-24 10:18:17.037) Features2d.cpp:1295::parseParameters() Init SiftData
[DEBUG] (2026-03-24 10:18:17.037) Memory.cpp:5351::createSignature() time keypoints (919) = 0.036290s
[DEBUG] (2026-03-24 10:18:17.037) Features2d.cpp:891::generateDescriptors() Descriptors extracted = 919, remaining kpts=919
[DEBUG] (2026-03-24 10:18:17.037) Memory.cpp:5357::createSignature() time descriptors (919) = 0.000036s
[DEBUG] (2026-03-24 10:18:17.037) Memory.cpp:5359::createSignature() ratio=0.500000, meanWordsPerLocation=499
[DEBUG] (2026-03-24 10:18:17.037) Memory.cpp:5506::createSignature() time keypoints 3D (919) = 0.000193s
[DEBUG] (2026-03-24 10:18:17.037) Memory.cpp:5736::createSignature() Joining dictionary update thread...
[DEBUG] (2026-03-24 10:18:17.037) Memory.cpp:5738::createSignature() Joining dictionary update thread... thread finished!
[DEBUG] (2026-03-24 10:18:17.037) Memory.cpp:5745::createSignature() time descriptor and memory update (919 of size=128) = 0.000013s
[DEBUG] (2026-03-24 10:18:17.037) Features2d.cpp:449::limitKeypoints() too much words (919), removing words with the hessian threshold
[DEBUG] (2026-03-24 10:18:17.037) Features2d.cpp:469::limitKeypoints() 419 keypoints removed, (kept 500), minimum response=2.639156
[DEBUG] (2026-03-24 10:18:17.037) Features2d.cpp:470::limitKeypoints() filter keypoints time = 0.000086 s
[DEBUG] (2026-03-24 10:18:17.037) VWDictionary.cpp:908::addNewWords() id=13481 descriptors=500
[DEBUG] (2026-03-24 10:18:17.037) VWDictionary.cpp:1009::addNewWords() newPts.total()=500 
terminate called after throwing an instance of 'cv::Exception'
  what():  OpenCV(4.5.4) /home/mathieu/workspace/opencv/modules/features2d/src/matchers.cpp:860: error: (-215:Assertion failed) trainDescCollection[iIdx].rows < IMGIDX_ONE in function 'knnMatchImpl'
```

**Comment by matlabbe** [comment] 2026-03-24 18:30
Solved: It seems that in my update process the parameter `Kp/NNStrategy` changed to 3 (bruteforce) instead of keeping the default (1=flann kd tree). Since the visual vocabulary is huge, it was reaching the limit of opencv's bruteforce algorithm, thus the assert happened. The solution was to relaunch with `Kp/NNStrategy=1`.
